pipeline {
    agent {
        label {
            label 'slave-1'
            customWorkspace '/mnt/war'
        }
    }
    stages {
        stage ('SCM') {
            steps {
                sh 'rm -rf *'
                sh 'git clone https://github.com/Satyam/new-project1.git'
            }
        }
        stage ('BUILD') {
            steps {
                 sh '''
                cd /mnt/war/new-project1/gameoflife-java21
                /mnt/build-tool/apache-maven-3.9.16/bin/mvn clean install
                '''
            }
        }
        stage ('UPLOAD-WAR-TO-S3') {
            steps {
                 sh '''
                aws s3 cp /mnt/war/new-project1/gameoflife-java21/target/gameoflife-java21-0.0.1-SNAPSHOT.war s3://war-gameoflife-satyam/
                '''
            }
        }
        stage ('DEPLOY-ON-SLAVE') {
            agent {
                label {
                    label 'slave-2'
                }
            }
            steps {
                 sh '''
                aws s3 cp s3://war-gameoflife-satyam/gameoflife-java21-0.0.1-SNAPSHOT.war /mnt/apache-tomcat-10.1.55/webapps/
                '''
            }
        }
    }
}
